const HOST="com.local.vless_xhttp_proxy",PORT=17890,ALARM="xray-health";let watchdog=null;
const nativeMessage=message=>new Promise((resolve,reject)=>chrome.runtime.sendNativeMessage(HOST,message,r=>{const e=chrome.runtime.lastError;e?reject(new Error(e.message)):r?resolve(r):reject(new Error("Native helper returned no response."));}));
async function setProxy(){const s=await chrome.storage.local.get({splitMode:"all",splitDomains:[]});if(s.splitMode==="all"||!s.splitDomains.length)return chrome.proxy.settings.set({scope:"regular",value:{mode:"fixed_servers",rules:{proxyForHttp:{scheme:"http",host:"127.0.0.1",port:PORT},proxyForHttps:{scheme:"http",host:"127.0.0.1",port:PORT},fallbackProxy:{scheme:"http",host:"127.0.0.1",port:PORT},bypassList:["<local>","localhost","127.0.0.1","[::1]"]}}});const domains=JSON.stringify(s.splitDomains),decision=s.splitMode==="only"?'if(match)return proxy;return "DIRECT";':'if(match)return "DIRECT";return proxy;';const data=`function FindProxyForURL(url,host){var d=${domains},proxy="PROXY 127.0.0.1:${PORT}",match=false;if(isPlainHostName(host)||host==="localhost"||host==="127.0.0.1")return "DIRECT";for(var i=0;i<d.length;i++){if(host===d[i]||dnsDomainIs(host,"."+d[i])){match=true;break;}}${decision}}`;return chrome.proxy.settings.set({scope:"regular",value:{mode:"pac_script",pacScript:{data}}});}
const clearProxy=()=>chrome.proxy.settings.clear({scope:"regular"});
async function privacy(on){try{if(on)await chrome.privacy.network.webRTCIPHandlingPolicy.set({scope:"regular",value:"disable_non_proxied_udp"});else await chrome.privacy.network.webRTCIPHandlingPolicy.clear({scope:"regular"});}catch(_){}}
async function publish(state,error="",activeProfileId=""){await chrome.storage.local.set({connectionState:state,lastError:error,activeProfileId});const icon=state==="connected"?"on":"off";await chrome.action.setIcon({path:{16:`icons/icon-${icon}-16.png`,32:`icons/icon-${icon}-32.png`}}).catch(()=>{});chrome.runtime.sendMessage({type:"state",state,error,activeProfileId}).catch(()=>{});}
function stopWatchdog(){if(watchdog){watchdog._intentional=true;watchdog.disconnect();watchdog=null;}}
function startWatchdog(){stopWatchdog();const p=chrome.runtime.connectNative(HOST);p._intentional=false;watchdog=p;p.onMessage.addListener(async m=>{if(m.event==="xray_stopped"){watchdog=null;await publish("error","Xray неожиданно завершился. VPN-трафик заблокирован до переподключения.","");}});p.onDisconnect.addListener(async()=>{if(watchdog===p)watchdog=null;if(!p._intentional)await publish("error","Потеряна связь с watchdog. Защитный proxy оставлен включённым.","");});p.postMessage({action:"watch"});}
async function connectProfile(id){const s=await chrome.storage.local.get({webrtcProtection:true});await chrome.storage.local.set({desiredConnected:true,lastProfileId:id});await publish("connecting","",id);const r=await nativeMessage({action:"connect",profileId:id});if(!r.ok)throw new Error(r.error||"Xray could not be started.");await setProxy();await privacy(s.webrtcProtection);startWatchdog();await publish("connected","",id);return{ok:true,state:"connected",activeProfileId:id};}
async function switchProfile(id){const s=await chrome.storage.local.get({webrtcProtection:true});await chrome.storage.local.set({desiredConnected:true,lastProfileId:id});await publish("reconnecting","",id);try{const r=await nativeMessage({action:"connect",profileId:id});if(!r.ok)throw new Error(r.error||"Не удалось переключить профиль.");await setProxy();await privacy(s.webrtcProtection);startWatchdog();await publish("connected","",id);return{ok:true,state:"connected",activeProfileId:id};}catch(e){await publish("error","Переподключение не удалось. VPN-трафик заблокирован.",id);throw e;}}
async function disconnect(){await chrome.storage.local.set({desiredConnected:false});stopWatchdog();await clearProxy();await privacy(false);let error="";try{const r=await nativeMessage({action:"disconnect"});if(!r.ok)error=r.error;}catch(e){error=e.message;}await publish("disconnected",error,"");return{ok:!error,state:"disconnected",error};}
async function reconcile(recover=false){const s=await chrome.storage.local.get({desiredConnected:false,lastProfileId:"",webrtcProtection:true});try{const r=await nativeMessage({action:"status"});if(r.ok&&r.connected){await setProxy();await privacy(s.webrtcProtection);if(!watchdog)startWatchdog();await publish("connected","",r.activeProfileId||s.lastProfileId);return{ok:true,state:"connected",activeProfileId:r.activeProfileId};}if(recover&&s.desiredConnected&&s.lastProfileId)return connectProfile(s.lastProfileId);if(s.desiredConnected){await publish("error","Xray остановлен. VPN-трафик остаётся заблокированным.");return{ok:false,state:"error",error:"Ожидается автоматическое переподключение."};}await clearProxy();await privacy(false);await publish("disconnected");return{ok:true,state:"disconnected"};}catch(e){if(!s.desiredConnected){await clearProxy();await privacy(false);}await publish("error",s.desiredConnected?"Helper недоступен. Защитный proxy оставлен включённым.":"Native helper unavailable. Run Setup.exe.");return{ok:false,state:"error",error:e.message};}}
chrome.runtime.onMessage.addListener((m,_s,send)=>{(async()=>{switch(m.action){case"status":return reconcile(false);case"connect":return connectProfile(m.profileId);case"switchProfile":return switchProfile(m.profileId);case"disconnect":return disconnect();case"profiles":return nativeMessage({action:"list_profiles"});case"saveProfile":return nativeMessage({action:"save_profile",id:m.id||"",name:m.name,country:m.country||"",url:m.url||""});case"deleteProfile":{const r=await nativeMessage({action:"delete_profile",id:m.id});if(r.disconnected)await disconnect();return r;}case"latency":return nativeMessage({action:"latency",id:m.id});case"checkIp":return nativeMessage({action:"check_ip"});case"updateXray":return nativeMessage({action:"update_xray"});case"settings":await chrome.storage.local.set(m.settings);if("webrtcProtection" in m.settings){const st=await chrome.storage.local.get("connectionState");if(st.connectionState==="connected")await privacy(m.settings.webrtcProtection);}if("splitMode" in m.settings||"splitDomains" in m.settings){const st=await chrome.storage.local.get("connectionState");if(st.connectionState==="connected")await setProxy();}return{ok:true};default:return{ok:false,error:"Unknown action."};}})().then(send).catch(async e=>{if(m.action==="connect"){await chrome.storage.local.set({desiredConnected:false});await clearProxy().catch(()=>{});await privacy(false);await publish("error",e.message,m.profileId||"");}send({ok:false,state:"error",error:e.message});});return true;});
async function ensureAlarm(){if(!await chrome.alarms.get(ALARM))await chrome.alarms.create(ALARM,{periodInMinutes:.5});}chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)reconcile(true);});chrome.runtime.onStartup.addListener(async()=>{const s=await chrome.storage.local.get({autoConnect:false,lastProfileId:""});if(s.autoConnect&&s.lastProfileId){await chrome.storage.local.set({desiredConnected:true});connectProfile(s.lastProfileId);}else reconcile(false);});chrome.runtime.onInstalled.addListener(ensureAlarm);ensureAlarm();
