const $=id=>document.getElementById(id);
let bridgeRequestId=0;const bridgePending=new Map(),bridgeStateListeners=[];
window.addEventListener("message",event=>{const m=event.data;if(event.source!==window.parent||!m)return;if(m.type==="vpn-response"){const pending=bridgePending.get(m.id);if(pending){bridgePending.delete(m.id);pending.resolve(m.result);}}else if(m.type==="vpn-state")for(const listener of bridgeStateListeners)listener(m.value);});
const bridge=(action,payload={})=>new Promise((resolve,reject)=>{const id=++bridgeRequestId;bridgePending.set(id,{resolve,reject});window.parent.postMessage({type:"vpn-request",id,action,payload},"*");setTimeout(()=>{if(bridgePending.delete(id))reject(new Error("Браузер не ответил на VPN-команду."));},50000);});
const send=(action,extra={})=>bridge(action,extra);
let profiles=[],editing="",currentState="disconnected";
const REGION_CODES=`AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW`.split(" ");
const COUNTRY_ALIASES={сша:"US",америка:"US",usa:"US",uk:"GB",англия:"GB",великобритания:"GB",россия:"RU",рф:"RU",голландия:"NL",нидерланды:"NL",оаэ:"AE",эмираты:"AE",южнаякорея:"KR",севернаякорея:"KP",чехия:"CZ",вьетнам:"VN",amsterdam:"NL",амстердам:"NL",newyork:"US",ньюйорк:"US",washington:"US",вашингтон:"US",losangeles:"US",лосанджелес:"US",london:"GB",лондон:"GB",paris:"FR",париж:"FR",berlin:"DE",берлин:"DE",frankfurt:"DE",франкфурт:"DE",warsaw:"PL",варшава:"PL",helsinki:"FI",хельсинки:"FI",stockholm:"SE",стокгольм:"SE",zurich:"CH",цюрих:"CH",vienna:"AT",вена:"AT",prague:"CZ",прага:"CZ",tokyo:"JP",токио:"JP",singapore:"SG",сингапур:"SG",istanbul:"TR",стамбул:"TR",dubai:"AE",дубай:"AE",moscow:"RU",москва:"RU"};
const normalizeCountry=value=>value.trim().toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f\s.'’()_-]/g,"").replace(/^the/,"");
const regionDisplays=[new Intl.DisplayNames(["ru"],{type:"region"}),new Intl.DisplayNames(["en"],{type:"region"})];
function countryCode(value){const n=normalizeCountry(value);if(!n)return"";const upper=value.trim().toUpperCase();if(/^[A-Z]{2}$/.test(upper)&&REGION_CODES.includes(upper))return upper;if(COUNTRY_ALIASES[n])return COUNTRY_ALIASES[n];for(const code of REGION_CODES)for(const display of regionDisplays)if(normalizeCountry(display.of(code)||"")===n)return code;return"";}
function flagSvg(value){const code=countryCode(value),horizontal={NL:["#ae1c28","#fff","#21468b"],RU:["#fff","#0039a6","#d52b1e"],DE:["#000","#dd0000","#ffce00"],AT:["#ed2939","#fff","#ed2939"],HU:["#ce2939","#fff","#477050"],BG:["#fff","#00966e","#d62612"],EE:["#4891d9","#000","#fff"],LT:["#fdb913","#006a44","#c8313e"],LU:["#ed2939","#fff","#00a1de"],PL:["#fff","#dc143c"],UA:["#0057b7","#ffd700"],ID:["#ce1126","#fff"],MC:["#ce1126","#fff"]},vertical={FR:["#0055a4","#fff","#ef4135"],IT:["#009246","#fff","#ce2b37"],IE:["#169b62","#fff","#ff883e"],BE:["#000","#fdda24","#ef3340"],RO:["#002b7f","#fcd116","#ce1126"]};let art="";
  if(horizontal[code]){const c=horizontal[code],h=32/c.length;art=c.map((x,i)=>`<path fill="${x}" d="M0 ${i*h}h48v${h}H0z"/>`).join("");}
  else if(vertical[code]){const c=vertical[code],w=48/c.length;art=c.map((x,i)=>`<path fill="${x}" d="M${i*w} 0h${w}v32H${i*w}z"/>`).join("");}
  else if(code==="JP")art='<path fill="#fff" d="M0 0h48v32H0z"/><circle fill="#bc002d" cx="24" cy="16" r="9"/>';
  else if(code==="CH")art='<path fill="#d52b1e" d="M0 0h48v32H0z"/><path fill="#fff" d="M20 7h8v6h6v7h-6v6h-8v-6h-6v-7h6z"/>';
  else if(code==="FI"||code==="SE"){const bg=code==="FI"?"#fff":"#006aa7",cross=code==="FI"?"#003580":"#fecc00";art=`<path fill="${bg}" d="M0 0h48v32H0z"/><path fill="${cross}" d="M14 0h6v32h-6zM0 13h48v6H0z"/>`;}
  else if(code==="TR")art='<path fill="#e30a17" d="M0 0h48v32H0z"/><circle fill="#fff" cx="20" cy="16" r="9"/><circle fill="#e30a17" cx="23" cy="16" r="7"/><circle fill="#fff" cx="30" cy="16" r="2"/>';
  else if(code==="US")art='<path fill="#fff" d="M0 0h48v32H0z"/><path stroke="#b22234" stroke-width="4" stroke-dasharray="4" d="M0 2h48M0 10h48M0 18h48M0 26h48"/><path fill="#3c3b6e" d="M0 0h21v17H0z"/><g fill="#fff"><circle cx="4" cy="4" r="1"/><circle cx="10" cy="4" r="1"/><circle cx="16" cy="4" r="1"/><circle cx="7" cy="9" r="1"/><circle cx="13" cy="9" r="1"/><circle cx="4" cy="14" r="1"/><circle cx="10" cy="14" r="1"/><circle cx="16" cy="14" r="1"/></g>';
  else if(code)art=`<defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#62748c"/><stop offset="1" stop-color="#344256"/></linearGradient></defs><path fill="url(#g)" d="M0 0h48v32H0z"/><text x="24" y="21" fill="#fff" font-family="Segoe UI,Arial" font-size="13" font-weight="700" text-anchor="middle">${code}</text>`;
  else art='<path fill="#e8ecf2" d="M0 0h48v32H0z"/><circle cx="24" cy="16" r="9" fill="none" stroke="#7c8798" stroke-width="2"/><path d="M15 16h18M24 7c4 4 4 14 0 18M24 7c-4 4-4 14 0 18" fill="none" stroke="#7c8798" stroke-width="1.5"/>';
  return`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 32">${art}</svg>`)}`;
}

function applyTheme(value){document.documentElement.dataset.theme=value==="auto"?"":value;}
function isBusy(){return ["connecting","reconnecting","disconnecting"].includes(currentState);}
function syncControls(){const busy=isBusy(),empty=!profiles.length;for(const id of["add","edit","ping","remove","profileTrigger","checkIp"])$(id).disabled=busy||(empty&&id!=="add");$("primaryAction").disabled=busy||empty;}
function state(value,error="",detail=""){
  currentState=value;document.body.dataset.state=value;
  const names={connected:"Подключено",connecting:"Подключение…",reconnecting:"Переподключение…",disconnecting:"Отключение…",error:"Защита остановлена",disconnected:"Отключено"};
  $("status").className=`connection ${value}`;$("statusText").textContent=names[value]||value;
  $("detail").textContent=detail||(value==="connected"?"Трафик защищён":value==="reconnecting"?"Смена сервера":value==="connecting"||value==="disconnecting"?"Пожалуйста, подождите":"Прямое подключение");
  $("error").textContent=error;$("primaryLabel").textContent=value==="connected"?"Отключить":value==="connecting"?"Подключение…":value==="reconnecting"?"Переподключение…":value==="disconnecting"?"Отключение…":"Подключить";$("primaryAction").setAttribute("aria-label",$("primaryLabel").textContent);syncControls();
}

function setSettingChoice(id,value,emit=false){const input=$(id),box=document.querySelector(`.setting-select[data-select="${id}"]`),option=box.querySelector(`[data-value="${value}"]`)||box.querySelector("[data-value]");input.value=option.dataset.value;box.querySelector(".setting-trigger span").textContent=option.textContent;for(const b of box.querySelectorAll("[data-value]"))b.classList.toggle("selected",b===option);box.classList.remove("open");if(emit)input.dispatchEvent(new Event("change"));}
function setThemeChoice(value,emit=false){const input=$("theme");input.value=value;for(const button of document.querySelectorAll("[data-theme-value]")){const selected=button.dataset.themeValue===value;button.classList.toggle("selected",selected);button.setAttribute("aria-checked",String(selected));}if(emit)input.dispatchEvent(new Event("change"));}
function profileFlag(p){return flagSvg(p?.country||p?.name||"");}
function selectProfile(id){const p=profiles.find(x=>x.id===id)||profiles[0];$("profile").value=p?.id||"";$("profileLabel").textContent=p?.name||"Нет профилей";$("profileFlag").src=profileFlag(p);$("profileFlag").alt=p?.country?`Флаг: ${p.country}`:"";for(const b of $("profileMenu").querySelectorAll("button"))b.classList.toggle("selected",b.dataset.id===$("profile").value);$("profileMenu").classList.remove("open");$("profileTrigger").setAttribute("aria-expanded","false");syncControls();}
async function chooseProfile(id){const previous=$("profile").value;if(id===previous){selectProfile(id);return;}selectProfile(id);if(currentState==="connected"){state("reconnecting");const r=await send("switchProfile",{profileId:id});state(r.state||"error",r.error||"");}else await send("settings",{settings:{lastProfileId:id}});}
async function loadProfiles(selected=""){const r=await send("profiles");if(!r.ok)throw new Error(r.error);profiles=r.profiles||[];$("profileMenu").replaceChildren(...profiles.map(p=>{const b=document.createElement("button");b.type="button";b.role="option";b.dataset.id=p.id;const f=document.createElement("img"),n=document.createElement("span");f.className="menu-flag";f.src=profileFlag(p);f.alt="";n.textContent=p.name;b.append(f,n);b.onclick=()=>chooseProfile(p.id);return b;}));selectProfile(selected);}
function openProfile(p){editing=p?.id||"";$("dialogTitle").textContent=p?"Изменить профиль":"Новый профиль";$("name").value=p?.name||"";$("country").value=p?.country||"";$("countryFlag").src=flagSvg(p?.country||p?.name||"");$("url").value="";$("url").placeholder=p?"Оставьте пустым, чтобы не менять":"vless://…";$("urlHint").textContent=p?"Текущий ключ скрыт. Новый URL заменит его.":"После сохранения ключ шифруется и скрывается.";$("modalError").textContent="";$("profileDialog").showModal();}

$("profileTrigger").onclick=e=>{e.stopPropagation();if(isBusy())return;const open=$("profileMenu").classList.toggle("open");$("profileTrigger").setAttribute("aria-expanded",String(open));};
document.addEventListener("click",()=>{$("profileMenu").classList.remove("open");$("profileTrigger").setAttribute("aria-expanded","false");for(const box of document.querySelectorAll(".setting-select"))box.classList.remove("open");});
for(const box of document.querySelectorAll(".setting-select")){box.querySelector(".setting-trigger").onclick=e=>{e.stopPropagation();for(const other of document.querySelectorAll(".setting-select"))if(other!==box)other.classList.remove("open");box.classList.toggle("open");};for(const option of box.querySelectorAll("[data-value]"))option.onclick=()=>setSettingChoice(box.dataset.select,option.dataset.value,true);}
for(const button of document.querySelectorAll("[data-theme-value]"))button.onclick=()=>setThemeChoice(button.dataset.themeValue,true);

$("add").onclick=()=>openProfile();$("edit").onclick=()=>openProfile(profiles.find(p=>p.id===$("profile").value));
function updateCountryPreview(){$("countryFlag").src=flagSvg($("country").value||$("name").value);}
$("country").oninput=updateCountryPreview;$("name").oninput=()=>{if(!$("country").value)updateCountryPreview();};
$("save").onclick=async e=>{e.preventDefault();const name=$("name").value.trim(),country=$("country").value.trim(),url=$("url").value.trim().replace(/\\(?=[:@_\-])/g,"");if(!name||(!editing&&!url))return $("modalError").textContent="Укажите название и VLESS URL.";const r=await send("saveProfile",{id:editing,name,country,url});if(!r.ok)return $("modalError").textContent=r.error;$("profileDialog").close();await loadProfiles(r.id);};
$("remove").onclick=async()=>{const id=$("profile").value,p=profiles.find(x=>x.id===id);if(!p||!confirm(`Удалить «${p.name}»?`))return;const r=await send("deleteProfile",{id});if(!r.ok)return state("error",r.error);await loadProfiles();state("disconnected");};
$("primaryAction").onclick=async()=>{if(currentState==="connected"){state("disconnecting");const r=await send("disconnect");state(r.state||"error",r.error||"");}else{state("connecting");const r=await send("connect",{profileId:$("profile").value});state(r.state||"error",r.error||"");}};
$("ping").onclick=async()=>{const r=await send("latency",{id:$("profile").value});state(currentState,r.error||"",r.ok?`Сервер отвечает · ${r.latencyMs} мс`:"");};
$("checkIp").onclick=async()=>{const r=await send("checkIp");state(r.ok?currentState:"error",r.error||"",r.ok?`Внешний IP · ${r.ip}`:"");};
$("settingsBtn").onclick=()=>$("settingsDialog").showModal();
$("theme").onchange=async()=>{applyTheme($("theme").value);await send("settings",{settings:{theme:$("theme").value}});};
for(const id of["autoConnect","webrtc"])$(id).onchange=()=>send("settings",{settings:{[id==="webrtc"?"webrtcProtection":"autoConnect"]:$(id).checked}});
function domains(){const out=[];for(let d of $("domains").value.split(/\r?\n/)){d=d.trim().toLowerCase().replace(/^https?:\/\//,"").split("/")[0].replace(/^\.+|\.+$/g,"");if(!d)continue;if(!/^(?:[a-z0-9-]+\.)*[a-z0-9-]+$/.test(d)&&!/^(?:\d{1,3}\.){3}\d{1,3}$/.test(d))throw new Error(`Некорректный домен: ${d}`);if(!out.includes(d))out.push(d);}return out;}
async function saveSplit(){try{$("settingsError").textContent="";await send("settings",{settings:{splitMode:$("splitMode").value,splitDomains:domains()}});}catch(e){$("settingsError").textContent=e.message;}}
$("splitMode").onchange=saveSplit;$("domains").onchange=saveSplit;$("update").onclick=async()=>{$("settingsError").textContent="";const r=await send("updateXray");$("settingsError").textContent=r.ok?(r.message||"Xray уже обновлён."):r.error;};
bridgeStateListeners.push(m=>{if(m?.activeProfileId)selectProfile(m.activeProfileId);state(m?.state||"error",m?.error||"");});
(async()=>{try{const s={autoConnect:false,webrtcProtection:true,lastProfileId:"",theme:"dark",splitMode:"all",splitDomains:[],...await bridge("__settingsGet")};applyTheme(s.theme);setThemeChoice(s.theme);$("autoConnect").checked=s.autoConnect;$("webrtc").checked=s.webrtcProtection;setSettingChoice("splitMode",s.splitMode);$("domains").value=(s.splitDomains||[]).join("\n");await loadProfiles(s.lastProfileId);const r=await send("status");state(r.state||"error",r.error||"");}catch(e){state("error",e.message);}})();
