const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)],tabStrip=$("#tabStrip"),compactToolbar=$(".compact-toolbar"),compactTabsAnchor=$("#compactTabsAnchor"),sidebar=$("#sidebar"),sidebarButton=$("#sidebarButton"),backButton=$("#backButton"),favoritesPanel=$("#favoritesPanel"),downloadsButton=$("#downloadsButton"),downloadsPanel=$("#downloadsPanel"),downloadsBadge=$("#downloadsBadge"),vpnPanel=$("#vpnPanel"),vpnFrame=$("#vpnFrame"),settingsPanel=$("#settingsPanel"),sidebarButtons=[sidebarButton,$("#compactSidebarButton")],backButtons=[backButton,$("#compactBackButton")],favoritesButtons=[],downloadsButtons=[downloadsButton,$("#compactDownloadsButton")],downloadsBadges=[downloadsBadge,$("#compactDownloadsBadge")],vpnButtons=[$("#vpnButton"),$("#vpnButtonRight"),$("#compactVpnButton"),$("#compactVpnButtonRight")],settingsButtons=[];
let state={tabs:[],page:null,settings:{layout:"classic",theme:"system",language:"ru",mattePanel:false,addressOpenMode:"current",addressPosition:"center",extensionsPosition:"left",downloadsMode:"dynamic"}},rightPanel="",editing=false,token=0,lastDownloads=[],downloadHideTimer=0,vpnState="disconnected",vpnBusy=false;
const I={
ru:{tabs:"Вкладки",back:"Назад",favorites:"Избранное",downloads:"Загрузки",share:"Поделиться",newTab:"Новая вкладка",settings:"Настройки",minimize:"Свернуть",maximize:"Развернуть",restore:"Восстановить",close:"Закрыть",reload:"Обновить",stop:"Остановить",addressPlaceholder:"Поиск или адрес",savedPages:"Сохранённые страницы",recentDownloads:"Текущие и недавние",appearance:"Оформление",classic:"Классический",classicHint:"Адрес сверху, вкладки ниже",compact:"Компактный",compactHint:"Всё в одной строке",theme:"Тема",system:"Системная",light:"Светлая",dark:"Тёмная",mattePanel:"Матовая панель",mattePanelHint:"Полупрозрачность и мягкий градиент",language:"Язык",search:"Поиск",defaultSearch:"Поисковая система",searchHint:"Используется для запросов из адресной строки",addressBehavior:"Переход из адресной строки",addressBehaviorHint:"Куда открывать введённый адрес",openCurrentTab:"В текущей вкладке",openNewIfOccupied:"В новой, если текущая занята",startup:"Стартовая страница",blankPage:"Пустая страница",customPage:"Свой адрес",askDownload:"Всегда спрашивать место сохранения",choose:"Выбрать…",vpnSettings:"Настройки VPN",vpnHint:"Профили, подключение и защита WebRTC",open:"Открыть",googleAccounts:"Учётные записи Google",googleHint:"Можно добавить несколько аккаунтов. Они работают в общей сессии браузера; синхронизация Chrome не включается.",addAccount:"Добавить аккаунт",manageAccounts:"Управление",passwords:"Пароли",passwordHint:"Пароли шифруются средствами Windows и хранятся рядом с данными браузера. Автозаполнение пока не выполняется.",site:"Сайт",login:"Логин",password:"Пароль",save:"Сохранить",opened:"открыто",emptyDownloads:"Загрузок пока нет",downloadHint:"Текущие и недавние файлы появятся здесь",done:"Готово",cancelled:"Отменено",error:"Ошибка",emptyFavorites:"Избранное пусто",favoriteHint:"Нажмите звезду, чтобы сохранить текущую страницу",find:"Найти на странице:",searchFor:"Искать",openTab:"Открытая вкладка",bookmark:"Избранное",history:"История",copyLogin:"Копировать логин",copyPassword:"Копировать пароль",remove:"Удалить",noPasswords:"Сохранённых паролей пока нет",fillPassword:"Заполните сайт, логин и пароль.",folderNone:"Папка не выбрана"},
en:{tabs:"Tabs",back:"Back",favorites:"Favorites",downloads:"Downloads",share:"Share",newTab:"New Tab",settings:"Settings",minimize:"Minimize",maximize:"Maximize",restore:"Restore",close:"Close",reload:"Reload",stop:"Stop",addressPlaceholder:"Search or enter address",savedPages:"Saved pages",recentDownloads:"Current and recent",appearance:"Appearance",classic:"Classic",classicHint:"Address bar above tabs",compact:"Compact",compactHint:"Everything in one row",theme:"Theme",system:"System",light:"Light",dark:"Dark",mattePanel:"Matte toolbar",mattePanelHint:"Translucency with a soft gradient",language:"Language",search:"Search",defaultSearch:"Search engine",searchHint:"Used for address bar queries",addressBehavior:"Address bar navigation",addressBehaviorHint:"Where entered addresses should open",openCurrentTab:"In the current tab",openNewIfOccupied:"New tab if current is occupied",startup:"Start page",blankPage:"Blank page",customPage:"Custom address",askDownload:"Always ask where to save files",choose:"Choose…",vpnSettings:"VPN Settings",vpnHint:"Profiles, connection and WebRTC protection",open:"Open",googleAccounts:"Google Accounts",googleHint:"You can add multiple accounts. They share this browser session; Chrome Sync is not enabled.",addAccount:"Add account",manageAccounts:"Manage",passwords:"Passwords",passwordHint:"Passwords are encrypted by Windows and stored with browser data. Autofill is not available yet.",site:"Website",login:"Username",password:"Password",save:"Save",opened:"open",emptyDownloads:"No downloads yet",downloadHint:"Current and recent files will appear here",done:"Done",cancelled:"Cancelled",error:"Error",emptyFavorites:"Favorites are empty",favoriteHint:"Use the star to save the current page",find:"Find on page:",searchFor:"Search for",openTab:"Open tab",bookmark:"Favorite",history:"History",copyLogin:"Copy username",copyPassword:"Copy password",remove:"Remove",noPasswords:"No saved passwords yet",fillPassword:"Enter a website, username and password.",folderNone:"Folder not selected"}};
Object.assign(I.ru,{pageMenu:"Действия страницы",toolbar:"Верхняя панель",addressPosition:"Положение адресной строки",addressPositionHint:"По центру или слева",extensionsPosition:"Закреплённые расширения",extensionsPositionHint:"Относительно адресной строки",downloadsVisibility:"Иконка загрузок",downloadsVisibilityHint:"Автоскрытие или постоянное отображение",center:"По центру",left:"Слева",leftOfAddress:"Слева",rightOfAddress:"Справа",dynamic:"Динамически",always:"Всегда",vpnOn:"VPN включён",vpnOff:"VPN выключен",vpnBusy:"VPN переключается"});
Object.assign(I.en,{pageMenu:"Page actions",toolbar:"Toolbar",addressPosition:"Address bar position",addressPositionHint:"Centered or left aligned",extensionsPosition:"Pinned extensions",extensionsPositionHint:"Relative to the address bar",downloadsVisibility:"Downloads icon",downloadsVisibilityHint:"Auto-hide or always visible",center:"Centered",left:"Left",leftOfAddress:"Left",rightOfAddress:"Right",dynamic:"Dynamic",always:"Always",vpnOn:"VPN on",vpnOff:"VPN off",vpnBusy:"VPN is switching"});
const tr=(k)=>I[state.settings?.language||"ru"]?.[k]||k;
function esc(v){const e=document.createElement("span");e.textContent=v??"";return e.innerHTML;}
function fav(x,c="favicon"){return x?.favicon?`<img class="${c}" src="${esc(x.favicon)}" alt="">`:`<span class="${c} favicon-fallback">●</span>`;}
function fallbacks(root){root.querySelectorAll("img.favicon,img.sidebar-favicon,img.list-favicon").forEach((i)=>i.addEventListener("error",()=>{const s=document.createElement("span");s.className=`${i.className} favicon-fallback`;s.textContent="●";i.replaceWith(s);},{once:true}));}
function translate(){document.documentElement.lang=state.settings.language;document.querySelectorAll("[data-i18n]").forEach((e)=>e.textContent=tr(e.dataset.i18n));document.querySelectorAll("[data-i18n-title]").forEach((e)=>{e.title=tr(e.dataset.i18nTitle);e.setAttribute("aria-label",e.title);});document.querySelectorAll("[data-i18n-placeholder]").forEach((e)=>e.placeholder=tr(e.dataset.i18nPlaceholder));}
function appearance(){document.body.dataset.layout=["classic","compact"].includes(state.settings.layout)?state.settings.layout:"classic";document.body.dataset.theme=state.settings.theme||"system";document.body.dataset.matte=state.settings.mattePanel?"true":"false";document.body.dataset.addressPosition=state.settings.addressPosition||"center";document.body.dataset.extensionsPosition=state.settings.extensionsPosition||"left";translate();syncDownloadVisibility();}
function sourceLabel(s){return s==="tab"?tr("openTab"):s==="bookmark"?tr("bookmark"):s==="history"?tr("history"):tr("search");}
function hideSuggestions(box){box.classList.remove("visible");window.browserShell.setSuggestionsHeight(0);}
function drawSuggestions(box,items,q){q=String(q||"").trim();if(!q){hideSuggestions(box);return;}const rows=items.map((x)=>x.source==="search"?`<button type="button" class="suggestion-row" data-search="${esc(x.query)}"><b class="search-mark">⌕</b><span><strong>${esc(x.title)}</strong><small>${tr("searchFor")}</small></span><em>${tr("search")}</em></button>`:`<button type="button" class="suggestion-row" data-url="${esc(x.url)}">${fav(x)}<span><strong>${esc(x.title)}</strong><small>${esc(x.url)}</small></span><em>${sourceLabel(x.source)}</em></button>`).join("");box.innerHTML=rows+`<button type="button" class="suggestion-row" data-search="${esc(q)}"><b class="search-mark">⌕</b><span><strong>${tr("searchFor")} «${esc(q)}»</strong></span><em>${tr("search")}</em></button>`;box.classList.add("visible");window.browserShell.setSuggestionsHeight(Math.min(390,box.querySelectorAll(".suggestion-row").length*44+18));fallbacks(box);box.querySelectorAll("[data-url]").forEach((b)=>b.onmousedown=(e)=>{e.preventDefault();window.browserShell.navigate(b.dataset.url);hideSuggestions(box);});box.querySelectorAll("[data-search]").forEach((b)=>b.onmousedown=(e)=>{e.preventDefault();window.browserShell.navigate(e.currentTarget.dataset.search);hideSuggestions(box);});}
function bindAddress(form,input,box){let selected=-1;const refresh=async()=>{const n=++token,items=await window.browserShell.suggestions(input.value);if(n===token&&document.activeElement===input){drawSuggestions(box,items,input.value);selected=-1;}};form.onsubmit=(e)=>{e.preventDefault();editing=false;hideSuggestions(box);window.browserShell.navigate(input.value);input.blur();};input.onfocus=()=>{if(!editing)input.value=state.page?.url||"";editing=true;input.select();refresh();};input.oninput=refresh;input.onblur=()=>setTimeout(()=>{editing=false;input.value=state.page?.label||tr("newTab");hideSuggestions(box);},120);input.onkeydown=(e)=>{const rows=[...box.querySelectorAll(".suggestion-row")];if(e.key==="ArrowDown"&&rows.length){e.preventDefault();selected=Math.min(rows.length-1,selected+1);rows.forEach((r,i)=>r.classList.toggle("selected",i===selected));}else if(e.key==="ArrowUp"&&rows.length){e.preventDefault();selected=Math.max(0,selected-1);rows.forEach((r,i)=>r.classList.toggle("selected",i===selected));}else if(e.key==="Enter"&&selected>=0){e.preventDefault();rows[selected].dispatchEvent(new MouseEvent("mousedown",{bubbles:true}));}else if(e.key==="Escape"){hideSuggestions(box);input.blur();}};}
function activeTab(x){return`<form class="compact-active-tab" data-compact-rendered data-active-tab="${x.id}"><button class="tab-action page-action" type="button" data-page-menu title="${tr("pageMenu")}"><svg viewBox="0 0 20 20"><circle cx="5" cy="10" r="1"/><circle cx="10" cy="10" r="1"/><circle cx="15" cy="10" r="1"/></svg></button>${fav(x)}<input id="compactAddress" class="active-address" value="${esc(x.label)}" placeholder="${tr("addressPlaceholder")}" autocomplete="off" spellcheck="false"><button class="tab-action reload-action${x.loading?" loading":""}" type="button" data-reload title="${x.loading?tr("stop"):tr("reload")}"><svg class="reload-svg" viewBox="0 0 20 20"><path d="M15.4 7A6 6 0 1 0 16 12M15.5 4v3.5H12"/></svg><svg class="stop-svg" viewBox="0 0 20 20"><rect x="6.5" y="6.5" width="7" height="7" rx="1"/></svg></button><button class="tab-action close-action" type="button" data-close-active title="${tr("close")}">×</button><div class="suggestions active-suggestions" id="compactSuggestions"></div></form>`;}
function renderClassicTabs(){tabStrip.innerHTML=state.tabs.map((x)=>`<div class="classic-tab${x.active?" active":""}" data-tab-id="${x.id}">${fav(x)}<strong>${esc(x.title||x.label)}</strong><button data-close-tab="${x.id}">×</button></div>`).join("");fallbacks(tabStrip);tabStrip.querySelectorAll("[data-tab-id]").forEach((e)=>e.onclick=(v)=>{if(!v.target.closest("[data-close-tab]"))window.browserShell.switchTab(+e.dataset.tabId);});tabStrip.querySelectorAll("[data-close-tab]").forEach((b)=>b.onclick=(e)=>{e.stopPropagation();window.browserShell.closeTab(+b.dataset.closeTab);});const input=$("#classicAddress");if(document.activeElement!==input)input.value=state.page?.label||tr("newTab");$(".classic-reload").classList.toggle("loading",!!state.page?.loading);}
function renderCompactTabs(){const old=$("#compactAddress"),keep=editing&&old,value=keep?old.value:"";compactToolbar.querySelectorAll("[data-compact-rendered]").forEach((node)=>node.remove());const fragment=document.createRange().createContextualFragment(state.tabs.map((x)=>x.active?activeTab(x):`<button class="compact-tab" data-compact-rendered data-tab-id="${x.id}" title="${esc(x.title||x.label)}">${fav(x)}</button>`).join(""));compactTabsAnchor.after(fragment);fallbacks(compactToolbar);compactToolbar.querySelectorAll("[data-compact-rendered][data-tab-id]").forEach((b)=>b.onclick=()=>window.browserShell.switchTab(+b.dataset.tabId));const form=compactToolbar.querySelector("[data-active-tab]"),input=$("#compactAddress");if(!form)return;bindAddress(form,input,$("#compactSuggestions"));form.querySelector("[data-reload]").onclick=()=>window.browserShell.reload();form.querySelector("[data-close-active]").onclick=()=>window.browserShell.closeTab(state.activeTabId);form.querySelector("[data-page-menu]").onclick=()=>window.browserShell.pageMenu();if(keep){input.value=value;input.focus();}}
function renderTabs(){renderClassicTabs();renderCompactTabs();}
function renderSidebar(){const box=$("#sidebarTabs");$("#sidebarCount").textContent=`${state.tabs.length} ${tr("opened")}`;box.innerHTML=state.tabs.map((x)=>`<div class="sidebar-tab${x.active?" active":""}">${fav(x,"sidebar-favicon")}<button data-select="${x.id}"><strong>${esc(x.title||tr("newTab"))}</strong><small>${esc(x.label)}</small></button><button data-close="${x.id}">×</button></div>`).join("");fallbacks(box);box.querySelectorAll("[data-select]").forEach((b)=>b.onclick=()=>window.browserShell.switchTab(+b.dataset.select));box.querySelectorAll("[data-close]").forEach((b)=>b.onclick=()=>window.browserShell.closeTab(+b.dataset.close));}
function renderSettings(){const s=state.settings;document.querySelectorAll("[data-layout-choice]").forEach((b)=>b.classList.toggle("selected",b.dataset.layoutChoice===s.layout));$("#themeSelect").value=s.theme;$("#mattePanelToggle").checked=Boolean(s.mattePanel);$("#languageSelect").value=s.language;$("#searchEngineSelect").value=s.searchEngine;$("#addressOpenMode").value=s.addressOpenMode||"current";$("#addressPosition").value=s.addressPosition||"center";$("#extensionsPosition").value=s.extensionsPosition||"left";$("#downloadsMode").value=s.downloadsMode||"dynamic";document.querySelectorAll('[name="startPageMode"]').forEach((r)=>r.checked=r.value===s.startPageMode);$("#startPageUrl").value=s.startPageUrl||"";$("#startPageUrl").disabled=s.startPageMode!=="custom";$("#askDownloadLocation").checked=s.askDownloadLocation!==false;$("#downloadPathLabel").textContent=s.downloadPath||tr("folderNone");}
function renderState(v){state=v||state;appearance();backButtons.forEach((button)=>button.disabled=!state.page?.canGoBack);sidebar.classList.toggle("visible",!!state.sidebarVisible);sidebarButtons.forEach((button)=>button.classList.toggle("active",!!state.sidebarVisible));[$("#windowMaximize"),$("#compactWindowMaximize")].forEach((m)=>{m.title=state.maximized?tr("restore"):tr("maximize");m.innerHTML=state.maximized?'<svg viewBox="0 0 16 16"><rect x="5.5" y="3.5" width="7" height="7"/><path d="M10.5 10.5v2h-7v-7h2"/></svg>':'<svg viewBox="0 0 16 16"><rect x="3.5" y="3.5" width="9" height="9"/></svg>';});document.title=state.page?.title?`${state.page.title} — Soulu`:"Soulu";renderTabs();renderSidebar();renderSettings();}
function closePanel(){rightPanel="";[favoritesPanel,downloadsPanel,vpnPanel,settingsPanel].forEach((x)=>x.classList.remove("open"));[...favoritesButtons,...downloadsButtons,...vpnButtons,...settingsButtons].forEach((x)=>x.classList.remove("active"));window.browserShell.setRightPanel(0);}
function openPanel(type){if(rightPanel===type)return closePanel();closePanel();rightPanel=type;const map={favorites:[favoritesPanel,favoritesButtons,330],downloads:[downloadsPanel,downloadsButtons,350],vpn:[vpnPanel,vpnButtons,390],settings:[settingsPanel,settingsButtons,440]},[panel,buttons,width]=map[type];panel.classList.add("open");buttons.forEach((button)=>button.classList.add("active"));window.browserShell.setRightPanel(width);}
function bytes(n){n=+n||0;return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
function syncDownloadVisibility(){const active=lastDownloads.some((x)=>x.state==="progressing"),always=state.settings?.downloadsMode==="always";downloadsButtons.forEach((button)=>{button.classList.toggle("auto-hidden",!always&&!active&&!button.dataset.recent);button.classList.toggle("is-downloading",active);});}
function renderDownloads(items){items=items||[];const hadActive=lastDownloads.some((x)=>x.state==="progressing"),activeItems=items.filter((x)=>x.state==="progressing"),n=activeItems.length;lastDownloads=items;downloadsBadges.forEach((badge)=>{badge.textContent=n?String(n):"";badge.classList.toggle("visible",n>0);});if(n){clearTimeout(downloadHideTimer);downloadsButtons.forEach((button)=>{button.dataset.recent="true";});}else if(hadActive){clearTimeout(downloadHideTimer);downloadsButtons.forEach((button)=>{button.dataset.recent="true";});downloadHideTimer=setTimeout(()=>{downloadsButtons.forEach((button)=>delete button.dataset.recent);syncDownloadVisibility();},30000);}syncDownloadVisibility();const box=$("#downloadsList");if(!items.length){box.innerHTML=`<div class="empty"><b>↓</b><strong>${tr("emptyDownloads")}</strong><small>${tr("downloadHint")}</small></div>`;return;}box.innerHTML=items.map((x)=>`<div class="download-row"><b>↓</b><span><strong>${esc(x.filename)}</strong><small>${x.state==="completed"?tr("done"):x.state==="cancelled"?tr("cancelled"):x.state==="interrupted"?tr("error"):`${bytes(x.receivedBytes)} / ${bytes(x.totalBytes)}`}</small></span></div>`).join("");}
function renderBookmarks(items){items=items||[];const box=$("#favoritesList");if(!items.length){box.innerHTML=`<div class="empty"><b>☆</b><strong>${tr("emptyFavorites")}</strong><small>${tr("favoriteHint")}</small></div>`;return;}box.innerHTML=items.map((x)=>`<div class="favorite-row">${fav(x,"list-favicon")}<button data-open="${esc(x.url)}"><strong>${esc(x.title)}</strong><small>${esc(x.url)}</small></button><button data-remove="${x.id}">×</button></div>`).join("");fallbacks(box);box.querySelectorAll("[data-open]").forEach((b)=>b.onclick=()=>{window.browserShell.openBookmark(b.dataset.open);closePanel();});box.querySelectorAll("[data-remove]").forEach((b)=>b.onclick=async()=>renderBookmarks(await window.browserShell.removeBookmark(+b.dataset.remove)));}
function renderPasswords(items){items=items||[];const box=$("#passwordList");if(!items.length){box.innerHTML=`<div class="mini-empty">${tr("noPasswords")}</div>`;return;}box.innerHTML=items.map((x)=>`<div class="password-row"><span><strong>${esc(x.site)}</strong><small>${esc(x.username)}</small></span><div><button data-user="${x.id}" title="${tr("copyLogin")}">U</button><button data-pass="${x.id}" title="${tr("copyPassword")}">•••</button><button data-delete="${x.id}">×</button></div></div>`).join("");box.querySelectorAll("[data-user]").forEach((b)=>b.onclick=()=>window.browserShell.copyPassword(+b.dataset.user,"username"));box.querySelectorAll("[data-pass]").forEach((b)=>b.onclick=()=>window.browserShell.copyPassword(+b.dataset.pass,"password"));box.querySelectorAll("[data-delete]").forEach((b)=>b.onclick=async()=>renderPasswords(await window.browserShell.removePassword(+b.dataset.delete)));}
async function setSetting(p){state.settings=await window.browserShell.setSettings(p);appearance();renderTabs();renderSettings();}
function vpnPost(m){vpnFrame.contentWindow?.postMessage(m,"*");}
function updateVpnState(v={}){vpnState=v.state||"disconnected";vpnBusy=["connecting","reconnecting","disconnecting"].includes(vpnState);const connected=vpnState==="connected",title=vpnBusy?tr("vpnBusy"):connected?tr("vpnOn"):tr("vpnOff");$$('#vpnToolbarIcon,#vpnToolbarIconRight,#compactVpnToolbarIcon,#compactVpnToolbarIconRight').forEach((icon)=>icon.src=connected?"vpn/icons/icon-on-32.svg":"vpn/icons/icon-off-32.svg");vpnButtons.forEach((button)=>{button.disabled=vpnBusy;button.classList.toggle("connected",connected);button.classList.toggle("busy",vpnBusy);button.setAttribute("aria-pressed",String(connected));button.title=title;});vpnPost({type:"vpn-state",value:v});}
async function toggleVpn(){if(vpnBusy)return;vpnBusy=true;updateVpnState({state:vpnState==="connected"?"disconnecting":"connecting"});try{if(vpnState==="connected"||vpnState==="disconnecting")return updateVpnState(await window.vpn.send("disconnect"));const settings=await window.vpn.settingsGet();if(!settings.lastProfileId){vpnBusy=false;updateVpnState({state:"disconnected"});openPanel("vpn");return;}updateVpnState(await window.vpn.send("connect",{profileId:settings.lastProfileId}));}catch(error){updateVpnState({state:"error",error:error.message});}}

bindAddress($("#classicAddressForm"),$("#classicAddress"),$("#classicSuggestions"));
sidebarButtons.forEach((button)=>button.onclick=()=>window.browserShell.toggleSidebar());
backButtons.forEach((button)=>button.onclick=()=>window.browserShell.back());
downloadsButtons.forEach((button)=>button.onclick=async()=>{if(!lastDownloads.some((x)=>x.state==="progressing"))delete button.dataset.recent;renderDownloads(await window.browserShell.getDownloads());openPanel("downloads");});
[$("#newTabButton"),$("#compactNewTabButton")].forEach((button)=>button.onclick=()=>window.browserShell.newTab());
vpnButtons.forEach((button)=>button.onclick=toggleVpn);
$("#classicPageMenu").onclick=()=>window.browserShell.pageMenu();
$("#settingsClose").onclick=closePanel;
$("#sidebarNewTab").onclick=()=>window.browserShell.newTab();
$("#addFavoriteButton").onclick=async()=>renderBookmarks(await window.browserShell.addBookmark());
[$("#windowClose"),$("#compactWindowClose")].forEach((button)=>button.onclick=()=>window.browserShell.close());
[$("#windowMinimize"),$("#compactWindowMinimize")].forEach((button)=>button.onclick=()=>window.browserShell.minimize());
[$("#windowMaximize"),$("#compactWindowMaximize")].forEach((button)=>button.onclick=()=>window.browserShell.maximize());
$(".classic-reload").onclick=()=>window.browserShell.reload();
$("#classicCloseTab").onclick=()=>window.browserShell.closeTab(state.activeTabId);
document.querySelectorAll("[data-toolbar-surface]").forEach((surface)=>surface.addEventListener("contextmenu",(event)=>{if(event.target.closest("button,input,form,.classic-tab,.compact-tab,.compact-active-tab"))return;event.preventDefault();window.browserShell.toolbarMenu();}));
document.querySelectorAll("[data-layout-choice]").forEach((b)=>b.onclick=()=>setSetting({layout:b.dataset.layoutChoice}));
$("#themeSelect").onchange=(e)=>setSetting({theme:e.target.value});
$("#mattePanelToggle").onchange=(e)=>setSetting({mattePanel:e.target.checked});
$("#languageSelect").onchange=(e)=>setSetting({language:e.target.value});
$("#searchEngineSelect").onchange=(e)=>setSetting({searchEngine:e.target.value});
$("#addressOpenMode").onchange=(e)=>setSetting({addressOpenMode:e.target.value});
$("#addressPosition").onchange=(e)=>setSetting({addressPosition:e.target.value});
$("#extensionsPosition").onchange=(e)=>setSetting({extensionsPosition:e.target.value});
$("#downloadsMode").onchange=(e)=>setSetting({downloadsMode:e.target.value});
document.querySelectorAll('[name="startPageMode"]').forEach((r)=>r.onchange=()=>setSetting({startPageMode:r.value}));
$("#startPageUrl").onchange=(e)=>setSetting({startPageUrl:e.target.value});
$("#askDownloadLocation").onchange=(e)=>setSetting({askDownloadLocation:e.target.checked});
$("#chooseDownloadFolder").onclick=async()=>{await window.browserShell.chooseDownloadFolder();};
$("#openVpnSettings").onclick=()=>openPanel("vpn");
$("#addGoogleAccount").onclick=()=>{window.browserShell.addGoogleAccount();closePanel();};
$("#manageGoogleAccounts").onclick=()=>{window.browserShell.manageGoogleAccounts();closePanel();};
$("#savePassword").onclick=async()=>{const site=$("#passwordSite").value.trim(),username=$("#passwordUsername").value.trim(),password=$("#passwordValue").value;if(!site||!username||!password)return alert(tr("fillPassword"));try{renderPasswords(await window.browserShell.addPassword({site,username,password}));$("#passwordSite").value=$("#passwordUsername").value=$("#passwordValue").value="";}catch(e){alert(e.message);}};

window.addEventListener("message",async(e)=>{if(e.source!==vpnFrame.contentWindow||e.data?.type!=="vpn-request")return;const{id,action,payload}=e.data;let result;try{result=action==="__settingsGet"?await window.vpn.settingsGet():action==="__settingsSet"?await window.vpn.settingsSet(payload):await window.vpn.send(action,payload||{});}catch(error){result={ok:false,state:"error",error:error.message};}vpnPost({type:"vpn-response",id,result});});
window.vpn.onState(updateVpnState);
window.browserShell.onState(renderState);
window.browserShell.onDownloads(renderDownloads);
window.browserShell.onFocusAddress(()=>{const input=state.settings.layout==="classic"?$("#classicAddress"):$("#compactAddress");input?.focus();input?.select();});
window.browserShell.onRequestFind(()=>{const v=prompt(tr("find"));if(v)window.browserShell.find(v);});
window.browserShell.onOpenSettings(()=>openPanel("settings"));
window.browserShell.onOpenDownloads(async()=>{renderDownloads(await window.browserShell.getDownloads());openPanel("downloads");});
window.browserShell.onOpenFavorites(async()=>{renderBookmarks(await window.browserShell.getBookmarks());openPanel("favorites");});
window.browserShell.onOpenVpnSettings(()=>openPanel("vpn"));
Promise.all([window.browserShell.getState(),window.browserShell.getDownloads(),window.browserShell.getBookmarks(),window.browserShell.getPasswords(),window.vpn.send("status")]).then(([s,d,b,p,v])=>{renderState(s);renderDownloads(d);renderBookmarks(b);renderPasswords(p);updateVpnState(v);});
